The bug in PySnooper 1 is not reproducible because all tests pass on the buggy version.